### ISSUE TITLE
Fix Castling 

### ISSUE THREAD

**Issue by chezbgone** [ekzhang/chess-aops#3]
Create new booleans and checks that require rooks to not have moved.

**Comment by ekzhang** [comment]
+1

**Comment by ekzhang** [comment]
@chezbgone Why the close?

**Comment by chezbgone** [comment]
I thought it was fixed?

**Comment by ekzhang** [comment]
Still haven't fixed the issue with moving rooks.

**Comment by ekzhang** [comment]
Ok, that's been fixed. Issue now is only with castling through a threatened square.
